ENVIRONMENT = "simulation"
SYS_LOG_PATH = "/data/logs"

SYSTEM_ADMINS = "huteng"
LDAP_ADDR = "ldap.int.luojilab.com:389"

TASK_CENTER_HOST = "http://taskcenter.dev.sao.cn"

[app]
  args = []
  addr = ":1816"

  [app.logger]
    level = "DEBUG"
    name = "application"
#
# neo settings
#
[neo]
  [neo.logger]
  level = "INFO"

[gateway]
	testing = "10.174.88.128:9090"
	simulation = "10.30.94.26:9090"
	production = "10.30.94.26:9090"

[mongo]
	addr = "mongodb://10.30.250.220:27017"
	dbName = "taskcenter-admin-premaster"